---
config:
  theme: neo
---
flowchart TB
    A(["**Bot** Listens"]) --> C["**Bot** Detects **Workflow Activation Keyword**"]
    C -- Si --> n4["**Bot** Beeps"]
    n4 --> n3["**Bot** Sends Current **Prompt** w/ **Intent List** and **Json Response Spec**"]
    C -- No --> A
    n3 --> n5["**Bot** Opens **Socket** and Starts Sending **Audio**"]
    n5 --> n7["**Bot** Stops **Stream** When it Detects **Silence**"]
    n11["**STT Service** Transforms Speech 2 Text"] --> n23["**Bot** sends Text to LLM"]
    n15["**Bot** Transforms **Text to Speech** &amp; **Executes Automation**"] --> A
    n23 --> n24["**LLM** returns json reply"]
    n7 --> n11
    n24 --> n15
    n18["**Yellow** = **Local Bot**"]
    n19["**Green** = **Cloud LLM**"]
    n25["**Blue** = **Cloud STT**"]

    C@{ shape: diam}
    n7@{ shape: rect}
    n18@{ shape: rect}
    n19@{ shape: rect}
    n25@{ shape: rect}
    style A stroke:#FFD600
    style C stroke:#FFD600
    style n4 stroke:#FFD600
    style n3 stroke:#FFD600
    style n5 stroke:#FFD600
    style n7 stroke:#FFD600
    style n11 stroke:#2962FF
    style n23 stroke:#FFD600
    style n15 stroke:#FFD600
    style n24 stroke:#00C853
    style n18 stroke:#FFD600
    style n19 stroke:#00C853
    style n25 stroke:#2962FF
